[package]
name = "led_tree"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mihneabuz/led_tree.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
